routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/profile/{id}', 'UserController@showUserProfile')->middleware('mydata')->name('showuserprofile');
Route::post('/user/profile/{id}', 'UserController@updateUserProfile')->name('updateuserprofile');
Route::resource('/customer', 'CustomerController');
Route::get('/get-customer-list', 'CustomerController@list')->name('get-customer-list');
Route::post('/customer/import', 'CustomerController@import')->name('customer.import');
Route::resource('/supplier', 'SupplierController');
Route::get('/get-supplier-list', 'SupplierController@list')->name('get-supplier-list');
Route::resource('/employee', 'EmployeeController');
Route::resource('/category', 'CategoryController');
Route::get('/get-category-list', 'CategoryController@list')->name('get-category-list');
Route::resource('/unit', 'UnitController');
Route::get('/get-unit-list', 'UnitController@list')->name('get-unit-list');
Route::resource('/item', 'ItemController');
Route::get('/get-item-list', 'ItemController@list')->name('get-item-list');
Route::get('/pos', 'PosController@index')->name('posindex');
Route::post('/pos', 'PosController@addToCart')->name('posaddtocart');
Route::post('/deletecart', 'PosController@deleteCartItem')->name('deletecartitem');
Route::post('/deleteallcart', 'PosController@deleteAllCartItem')->name('deleteallcartitem');
Route::resource('/orderbook', 'OrderBookController');
Route::get('/get-order-book-list', 'OrderBookController@list')->name('get-order-book-list');
Route::get('/account', 'AccountController@index')->name('account.index');
Route::post('/account', 'AccountController@store')->name('account.store');
Route::post('/account/edit', 'AccountController@edit')->name('account.edit');
Route::delete('/account/{account}', 'AccountController@destroy')->name('account.destroy');
Route::post('/account/update', 'AccountController@update')->name('account.update');
Route::get('/error', 'ErrorController@err404')->name('404error');
Route::post('/pos/invoice', 'PosController@itemSellInvoiceShow')->name('sellInvoice.show');
Route::resource('/designation', 'DesignationController');
Route::resource('/pay-salary', 'PaySalaryController');
Route::resource('/attendance', 'AttendanceController');
Route::get('/get-attendance-list', 'AttendanceController@getAattendance')->name('get-attendance-list');
Route::resource('/daily-in', 'DailyInController');
Route::post('/get-daily-in-list', 'DailyInController@list')->name('get-daily-in-list');
Route::resource('/daily-out', 'DailyOutController');
Route::post('/get-daily-out-list', 'DailyOutController@list')->name('get-daily-out-list');
Route::resource('/share-holder', 'ShareHolderController');
Route::get('/get-share-holder', 'ShareHolderController@list')->name('get-share-holder');
Route::resource('/capital-management', 'CapitalManagementController');
Route::post('/get-capital-management-list', 'CapitalManagementController@list')->name('get-capital-management-list');
Route::resource('/buy', 'BuyController');
Route::get('/get-buy-list', 'BuyController@list')->name('get-buy-list');
Route::resource('/sell', 'SellController');
Route::get('/sell-buy-list', 'SellController@list')->name('sell-buy-list');
Route::post('/get-price', 'OrderBookController@getPrice')->name('get-price');
Route::resource('/stock', 'StockController');
Route::get('/get-stock-list', 'StockController@list')->name('get-stock-list');
Route::post('/get-stock-list-from-item', 'StockController@listFromItem')->name('get-stock-list-from-item');
Route::post('/stock/get-unit', 'StockController@getUnit')->name('stock.get-unit');

app/Models/Attendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    protected $guarded = [];

    public function employee(){
        $this->belongsTo(Employee::class,'employee_id', 'id');
    }
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Attendance;
use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class AttendanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = null;
        return view('attendances.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = Employee::with('today_attendance')->get();
        return view('attendances.take-attendance', compact('employees'));
    }

    public function getAattendance(){
        $data = Employee::select('*')->with('designation');

        return DataTables::of($data)
            ->editColumn('name', function($data){
                return $data->name;
            })
            ->editColumn('phone', function($data){
                return $data->phone;
            })
            ->addColumn('designation', function($data){
                return $data->designation->title;
            })
            ->addColumn('attendance', function($data){
                return $data->id;
            })
            ->addColumn('entry', function($data){
                return $data->id;
            })
            ->addColumn('exit', function($data){
                return $data->id;
            })
            ->addIndexColumn()
            ->make(true);
    }

    public function store(Request $request)
    {
        $input = array_chunk($request->except(['_token', 'DataTables_Table_0_length', 'get-attendance_length']),3, true);
        foreach ($input as $item) {
            $id = substr(array_keys($item)['0'], 0, strpos(array_keys($item)['0'], '_'));
            $data = [
                'employee_id' => $id,
                'attendance' => $item[$id.'_attendance'],
                'entry_time' => $item[$id.'_entry_time'],
                'exit_time' => $item[$id.'_exit_time'],
                'status' => 1,
                'created_by' => Auth::user()->id,
                'updated_at' => null
            ];
            if ($data['attendance'] == null && $data['entry_time'] == null && $data['exit_time'] == null){
                continue;
            }else{
                if ($data['entry_time'] != null || $data['exit_time'] != null){
                    $data['attendance'] = 1;
                }
                Attendance::create($data);
            }
        }
        return redirect()->back()->with('success', 'Attendance Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function show(Attendance $attendance)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function edit(Attendance $attendance)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Attendance $attendance)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attendance $attendance)
    {
        //
    }
}

resources/views/attendances/create.blade.php
@extends('layouts.pos')
@section('title', 'Employees')
@section('block-header', 'Add New Employee')
@section('breadcrumb')
    <ul class="nav navbar-nav navbar-left n-left">
        <li><a href="{{route('employee.index')}}">Employees</a></li>
        <li><a href="#">&#62;</a></li>
        <li><a href="{{route('employee.index')}}">Manage Designation</a></li>
        <li><a href="#">&#62;</a></li>
        <li><a href="#">Create</a></li>
    </ul>
@endsection
@section('content')
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="body">
                    @include('layouts.messages')
                    {!! Form::open(['route' => 'employee.store', 'method' => 'post']) !!}

                        @include('employees.form')

                        <div class="row">
                            <div style="text-align: center">
                                <a href="{{route('employee.index')}}" class="btn btn-primary">Back</a>
                                <button class="btn btn-success" type="submit">Submit</button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/attendances/delete-modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="confirm" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body t-center">
                <h3 style="color:#f44336;">Are you sure about Delete?</h3>
                <div class="modal-footer t-center">
                    <button type="button" class="btn btn-success btn-lg waves-effectr" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-danger btn-lg waves-effectr" id="delete-btn">Yes</button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/attendances/edit.blade.php
@extends('layouts.pos')
@section('title', 'Employees')
@section('block-header', 'Edit Employee')
@section('breadcrumb')
    <ul class="nav navbar-nav navbar-left n-left">
        <li><a href="{{route('employee.index')}}">Employees</a></li>
        <li><a href="#">&#62;</a></li>
        <li><a href="{{route('employee.index')}}">Manage Designation</a></li>
        <li><a href="#">&#62;</a></li>
        <li><a href="#">Edit</a></li>
    </ul>
@endsection

@section('content')
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="body">
                    @include('layouts.messages')
                    {!! Form::model($employee, ['route' => ['employee.update', $employee->id], 'method' => 'PATCH']) !!}

                        @include('employees.form')

                        <div class="row">
                            <div style="text-align: center">
                                <a href="{{route('employee.index')}}" class="btn btn-primary">Back</a>
                                <button class="btn btn-success" type="submit">Update</button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/attendances/filter.blade.php
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <i class="more-less glyphicon glyphicon-plus"></i>
{{--                    <i class="more-less glyphicon glyphicon-minus"></i>--}}
                    Filter
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                {!! Form::open(['route' => 'employee.store', 'method' => 'post', 'id'=>'filter']) !!}
                <div class="row clearfix">
                    <div class="col-sm-4">
                        {{ Form::radio('rang_or_month', '2', false, array('id'=>'month')) }}
                        {{ Form::label('month', 'Select Month & Year', ['style'=>'font-weight:bold']) }}
                        <div class="form-group">
                            <div class="form-line">
                                {!! Form::text('datepicker', null, ['class' => 'form-control', 'placeholder' => 'Disable Month & Year', 'id' => 'datepicker', 'disabled'=>'disabled']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        {{ Form::radio('rang_or_month', '1', false, array('id'=>'rang')) }}
                        {{ Form::label('rang', 'Select Date Rang', ['style'=>'font-weight:bold']) }}
                        <div class="form-group">
                            <div class="form-line">
                                {!! Form::text('datefilter', null, ['class' => 'form-control', 'id'=>'datefilter', 'placeholder' => 'Disable Date Rang', 'disabled'=>'disabled']) !!}
                            </div>
                        </div>
                    </div>
                    <div style="text-align: center" class="col-sm-4">
{{--                        <label for="designation">Salary Period</label>--}}
{{--                        <div class="form-group">--}}
{{--                            <div class="form-line">--}}
                        <br>
                                {!! Form::reset("<-- Reset Options", ['class' => 'btn btn-primary', 'onclick'=>'resetForm()']) !!}
{{--                            </div>--}}
{{--                        </div>--}}
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="col-sm-4">
                        <label for="designation">Salary Period</label>
                        <div class="form-group">
                            <div class="form-line">
                                {!! Form::select('salary_period[]', salary_period() ? ['0'=>'All']+salary_period() ?? [''=>''] : [''=>'']+['0'=>'All'], null, ['class' => 'form-control select2', 'multiple'=>'multiple']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <label for="designation">Designation</label>
                        <div class="form-group">
                            <div class="form-line">
                                {!! Form::select('designation[]', designations() ? ['0'=>'All']+designations() ?? [''=>''] : [''=>'']+['0'=>'All'], null, ['class' => 'form-control select2', 'multiple'=>'multiple']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <label for="designation">Employee</label>
                        <div class="form-group">
                            <div class="form-line">
                                {!! Form::select('employee[]', employees() ? ['0'=>'All']+employees() ?? [''=>''] : [''=>'']+['0'=>'All'], null, ['class' => 'form-control select2', 'multiple'=>'multiple']) !!}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div style="text-align: center">
                        <button class="btn btn-success" type="submit">Filter</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@push('css')
    <!-- Date Range Picker Css-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/css/datepicker.min.css" rel="stylesheet">
@endpush

@push('scripts')
    <!-- Date Range Picker Js -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>

    <script type="text/javascript">
        $(function() {
            $('input[name="datefilter"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: 'Clear'
                }
            });

            $('input[name="datefilter"]').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
            });

            $('input[name="datefilter"]').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
            });

        });

        //    month and year
        $("#datepicker").datepicker( {
            format: "mm-yyyy",
            startView: "months",
            minViewMode: "months",
            autoclose: true,
        });

        // datatable responsive
        // $('#DataTables_Table_0').DataTable( {
        //     responsive: true,
        // } );
    </script>


    <script>
        $("#month").click(function () {
            $('#datefilter').attr({disabled: true, placeholder: 'Disable Date Rang'});
            $('#datepicker').attr({disabled: false, placeholder: 'Select Month & Year'});
        });
        $("#rang").click(function () {
            $('#datefilter').attr({disabled: false, placeholder: 'Select Date Rang'});
            $('#datepicker').attr({disabled: true, placeholder: 'Disable Month & Year'});
        });
    </script>

    <script>
        function resetForm() {
            // alert('d');
            $('#filter')[0].reset();
            // document.getElementById("filter").reset();
        }
    </script>
@endpush

resources/views/attendances/form.blade.php
<div class="row clearfix">
    <div class="col-sm-6">
        <label for="name">Name (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Enter Employee Name', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="email">Email</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'Enter Employee Email']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="phone">Phone (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::text('phone', null, ['class' => 'form-control', 'placeholder' => 'Enter Employee Phone No.', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="nid">NID</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::text('nid', null, ['class' => 'form-control', 'placeholder' => 'Enter Employee NID No.']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="present_address">Present Address (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::textarea('present_address', null, ['class' => 'form-control', 'rows' => '4', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="present_address">Permanent Address (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::textarea('permanent_address', null, ['class' => 'form-control', 'rows' => '4', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="designation">Designation (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::select('designation_id', designations() ? [''=>'']+designations() ?? [''=>''] : [''=>''], null, ['class' => 'form-control select2', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="designation">Salary Period (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::select('salary_period', salary_period() ? [''=>'']+salary_period() ?? [''=>''] : [''=>''], null, ['class' => 'form-control select2', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="phone">Salary (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::number('salary', null, ['class' => 'form-control', 'placeholder' => 'Enter Employee Salary', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <label for="status">Status (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::select('status', ['1'=>'Active']+['2'=>'Inactive'], null, ['class' => 'form-control select2', 'required' => 'required']) !!}
            </div>
        </div>
    </div>
</div>

resources/views/attendances/index.blade.php
@extends('layouts.pos')
@section('title', 'Employees')
@section('block-header', 'Employees')

@section('content')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header t-end">
                    <a href="{{route('employee.create')}}" class="btn btn-danger waves-effect m-r-20">Add New Employee</a>
                </div>

                <div class="body">
                    @include('layouts.messages')
                    <div class="table-responsive">
                        <table data-form="deleteForm" class="table table-bordered table-striped table-hover js-basic-example dataTable js-exportable">
                            <thead class="thead-color">
                            <tr>
                                <th>Sl. No.</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Designation</th>
                                <th>Address</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
{{--                            @foreach($employees as $employee)--}}
{{--                                <tr>--}}
{{--                                    <td class="t-center">{{$loop->index+1}}</td>--}}
{{--                                    <td class="t-center">{{$employee->name}}</td>--}}
{{--                                    <td class="t-center">{{$employee->phone}}</td>--}}
{{--                                    <td class="t-center">{{$employee->designation}}</td>--}}
{{--                                    <td class="t-center">{{$employee->present_address}}</td>--}}
{{--                                    <td class="t-center">--}}
{{--                                        <a class="btn btn-primary waves-effect" href="{{route('employee.edit', $employee->id)}}">--}}
{{--                                            <i class="material-icons">mode_edit</i>--}}
{{--                                        </a>--}}
{{--                                        <form class="form-delete" style="display: inline;" action="{{route('employee.destroy', $employee->id)}}" method="post">--}}
{{--                                            {{ method_field('DELETE') }}--}}
{{--                                            @csrf--}}
{{--                                            <button data-toggle="modal" data-target=".delete-modal" class="btn btn-danger waves-effect" type="submit">--}}
{{--                                                <i class="material-icons">delete</i>--}}
{{--                                            </button>--}}
{{--                                        </form>--}}
{{--                                    </td>--}}
{{--                                </tr>--}}
{{--                            @endforeach--}}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('employees.delete-modal')
@endsection

resources/views/attendances/take-attendance.blade.php
@extends('layouts.pos')
@section('title', 'Employees')
@section('block-header', 'Employees')

@section('content')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            @include('attendances.filter')
            <div class="card">
                <div class="body">
                    @include('layouts.messages')
                    {{ Form::open(['route' => 'attendance.store', 'method' => 'post']) }}
                        <div class="t-end">
                            <button type="submit" class="btn btn-success waves-effect m-r-20">
                                Submit
                            </button>
                        </div>
                        <hr>
                        <table id="get-attendance" data-form="deleteForm" class="table table-bordered table-striped table-hover">
                            <thead class="thead-color">
                            <tr>
                                <th>SL</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Designation</th>
                                <th>Attendance</th>
                                <th>Entry Time</th>
                                <th>Exit Time</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <script>


        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#get-attendance').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                // scrollY: "500px",
                ajax: '{{ url('get-attendance-list') }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'id' },
                    { data: 'name', name: 'name'},
                    { data: 'phone', name: 'phone'},
                    { data: 'designation', name: 'designation'},
                    { data: 'attendance',
                        render:
                            function(data, type, row) {
                                return '<input type="hidden" name="'+data+'_attendance">'+
                                        '<div class="form-check form-check-inline">'+
                                        '<input class="form-check-input" type="radio" name="'+data+'_attendance" id="'+data+'_present" value="1">'+
                                        '<label style="color:#2b982b" class="form-check-label" for="'+data+'_present">Present</label>'+
                                        '</div>'+
                                        '<div class="form-check form-check-inline">'+
                                        '<input class="form-check-input" type="radio" name="'+data+'_attendance" id="'+data+'_absent" value="2">'+
                                        '<label style="color:#f44336" class="form-check-label" for="'+data+'_absent">Absent</label>'+
                                        '</div>'+
                                        '<div class="form-check form-check-inline">'+
                                        '<input class="form-check-input" type="radio" name="'+data+'_attendance" id="'+data+'_leave" value="0">'+
                                        '<label class="form-check-label" for="'+data+'_leave">On Leave</label>'+
                                        '</div>';
                            }
                    },
                    { data: 'entry',
                        render:
                            function(data, type, row) {
                                return '<input type="time" name="'+data+'_entry_time">';
                            }
                    },
                    { data: 'exit',
                        render:
                            function(data, type, row) {
                                return '<input type="time" name="'+data+'_exit_time">';
                            }
                    },
                    { data: 'designation', name: 'designation'},
                    // {data: 'action', name: 'action', orderable: false,
                    //     render:
                    //         function(data, type, row) {
                    //             // return '<span class="btn btn-primary" id="modalView" onclick="journalView('+data+')">Details</span>';
                    //             return '<div style="text-align:center" class="action-btn">'+
                    //                 '<span class="btn btn-primary btn-sm" id="modalView" onclick="journalView('+row.id+')">View</span>'+
                    //                 '<a class="btn btn-info btn-sm" href="deliveries/'+row.id+'/edit">Edit</a>'+
                    //                 '<a class="btn btn-rose btn-link" target="_blank" href="/print/delivery-info/'+row.id+'">Print</a>'+
                    //                 // '<span class="btn btn-danger btn-sm" onclick="deliveryDelete('+row.id+')">Delete</span>'+
                    //                 '</div>';
                    //         }
                    // },
                ],
            });
        });
    </script>
@endpush