routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/profile/{id}', 'UserController@showUserProfile')->middleware('mydata')->name('showuserprofile');
Route::post('/user/profile/{id}', 'UserController@updateUserProfile')->name('updateuserprofile');
Route::resource('/customer', 'CustomerController');
Route::get('/get-customer-list', 'CustomerController@list')->name('get-customer-list');
Route::post('/customer/import', 'CustomerController@import')->name('customer.import');
Route::resource('/supplier', 'SupplierController');
Route::get('/get-supplier-list', 'SupplierController@list')->name('get-supplier-list');
Route::resource('/employee', 'EmployeeController');
Route::resource('/category', 'CategoryController');
Route::get('/get-category-list', 'CategoryController@list')->name('get-category-list');
Route::resource('/unit', 'UnitController');
Route::get('/get-unit-list', 'UnitController@list')->name('get-unit-list');
Route::resource('/item', 'ItemController');
Route::get('/get-item-list', 'ItemController@list')->name('get-item-list');
Route::get('/pos', 'PosController@index')->name('posindex');
Route::post('/pos', 'PosController@addToCart')->name('posaddtocart');
Route::post('/deletecart', 'PosController@deleteCartItem')->name('deletecartitem');
Route::post('/deleteallcart', 'PosController@deleteAllCartItem')->name('deleteallcartitem');
Route::resource('/orderbook', 'OrderBookController');
Route::get('/get-order-book-list', 'OrderBookController@list')->name('get-order-book-list');
Route::get('/account', 'AccountController@index')->name('account.index');
Route::post('/account', 'AccountController@store')->name('account.store');
Route::post('/account/edit', 'AccountController@edit')->name('account.edit');
Route::delete('/account/{account}', 'AccountController@destroy')->name('account.destroy');
Route::post('/account/update', 'AccountController@update')->name('account.update');
Route::get('/error', 'ErrorController@err404')->name('404error');
Route::post('/pos/invoice', 'PosController@itemSellInvoiceShow')->name('sellInvoice.show');
Route::resource('/designation', 'DesignationController');
Route::resource('/pay-salary', 'PaySalaryController');
Route::resource('/attendance', 'AttendanceController');
Route::get('/get-attendance-list', 'AttendanceController@getAattendance')->name('get-attendance-list');
Route::resource('/daily-in', 'DailyInController');
Route::post('/get-daily-in-list', 'DailyInController@list')->name('get-daily-in-list');
Route::resource('/daily-out', 'DailyOutController');
Route::post('/get-daily-out-list', 'DailyOutController@list')->name('get-daily-out-list');
Route::resource('/share-holder', 'ShareHolderController');
Route::get('/get-share-holder', 'ShareHolderController@list')->name('get-share-holder');
Route::resource('/capital-management', 'CapitalManagementController');
Route::post('/get-capital-management-list', 'CapitalManagementController@list')->name('get-capital-management-list');
Route::resource('/buy', 'BuyController');
Route::get('/get-buy-list', 'BuyController@list')->name('get-buy-list');
Route::resource('/sell', 'SellController');
Route::get('/sell-buy-list', 'SellController@list')->name('sell-buy-list');
Route::post('/get-price', 'OrderBookController@getPrice')->name('get-price');
Route::resource('/stock', 'StockController');
Route::get('/get-stock-list', 'StockController@list')->name('get-stock-list');
Route::post('/get-stock-list-from-item', 'StockController@listFromItem')->name('get-stock-list-from-item');
Route::post('/stock/get-unit', 'StockController@getUnit')->name('stock.get-unit');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    public function items(){
        return $this->belongsToMany(Item::class, 'category_item');
    }

    public static function getAllCategoriesByArray()
    {
        try {
            // Validate the value...
            $datas = Category::all()->where('status', 1);
            if (count($datas) > 0){
                foreach ($datas as $item) {
                    $data[$item->id] = $item->name;
                }

                return $data;
            }

        } catch (\Throwable $e) {
            return false;
        }
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('items.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function list(){
        $data = Category::select('*');

        return DataTables::of($data)
            ->editColumn('name', function($data){
                return $data->name;
            })
            ->editColumn('code', function($data){
                return $data->code;
            })
            ->editColumn('description', function($data){
                return $data->description;
            })
            ->editColumn('status', function($data){
                return $data->status;
            })
            ->editColumn('created_by', function($data){
                return getUserById($data->created_by);
            })
            ->editColumn('updated_by', function($data){
                $user = getUserById($data->updated_by);
                return $user;
            })
            ->editColumn('created_at', function($data){
                return $data->created_at;
            })
            ->editColumn('updated_at', function($data){
                return $data->updated_at;
            })
            ->addColumn('action', function($data){
                return encrypt($data->id);
            })
            ->addIndexColumn()
            ->make(true);
    }

    public function create()
    {
        return view('items.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'name'  => 'required|unique:categories',
            'code'  =>  'required|unique:categories',
            'description'  =>  '',
        ]);
        $validatedData['status'] = 1;
        $validatedData['created_by'] = Auth::user()->id;
        $validatedData['updated_at'] = null;
        Category::create($validatedData);
        return redirect()->route('category.index')->with('success', 'Category Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = decrypt($id);
        $category = Category::find($id);
        return view('items.categories.edit', ['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $this->validate($request, [
            'name'  => 'required|unique:categories,name,'.$id,
            'code'  =>  'required|unique:categories,code,'.$id,
            'description'  =>  '',
            'status'  =>  '',
        ]);
        $validatedData['updated_by'] = Auth::user()->id;
        $updatingRow = Category::find($id);
        $updatingRow->update($validatedData);
        return redirect()->route('category.index')->with('success', 'Category Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delRow = Category::find($id);
        $delRow->delete();
        return redirect()->route('category.index')->with('success-message', 'Data Deleted Successfully');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Item;
use Faker\Provider\File;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::with('categories')->get();
        return view('items.index', ['items'=>$items]);
    }


    public function list(){
        $data = Item::select('*')->with('categories');
        return DataTables::of($data)
            ->editColumn('name', function($data){
                return $data->name;
            })
            ->editColumn('item_code', function($data){
                return $data->item_code;
            })
            ->editColumn('purchase_price', function($data){
                return $data->purchase_price;
            })
            ->editColumn('retail_price', function($data){
                return $data->retail_price;
            })
            ->editColumn('quantity', function($data){
                return $data->quantity;
            })
            ->editColumn('vat', function($data){
                return $data->vat;
            })
            ->editColumn('image', function($data){
                $url= asset('/images/items/'.$data->image);
                return '<img height="100" width="100" src="'.$url.'" alt="">';
            })
            ->editColumn('description', function($data){
                return $data->description;
            })
            ->addColumn('unit', function($data){
                return $data->unit ? $data->unit->name : '';
            })
            ->editColumn('category', function($data){
                $datas = [];
                foreach ($data->categories as $category){
                    $datas[] = $category->name;
                }

                return implode(" || ",$datas);
            })
            ->editColumn('status', function($data){
                return $data->status;
            })
            ->editColumn('created_by', function($data){
                return getUserById($data->created_by);
            })
            ->editColumn('updated_by', function($data){
                $user = getUserById($data->updated_by);
                return $user;
            })
            ->editColumn('created_at', function($data){
                return $data->created_at;
            })
            ->editColumn('updated_at', function($data){
                return $data->updated_at;
            })
            ->addColumn('action', function($data){
                return encrypt($data->id);
            })
            ->rawColumns(['image', 'action'])
            ->addIndexColumn()
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('items.create', ['categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */


    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'name'  =>  'required|unique:items',
            'item_code'  =>  'required',
            'unit_id'  =>  'required',
            'purchase_price'    =>  'required',
            'retail_price'      =>  '',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'vat'  =>  '',
            'category'  => 'required',
            'status'  => 'required',
        ]);

        $image = $request->file('image');
        if($request->hasFile('image')){
            $uploadedImage = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images/items');
            $image->move($destinationPath, $uploadedImage);
            $validatedData['image'] = $uploadedImage;
        }else{
            $validatedData['image'] = null;
        }

        $insertingRow = new Item();
        $insertingRow->name = $validatedData['name'];
        $insertingRow->item_code = $validatedData['item_code'];
        $insertingRow->purchase_price = $validatedData['purchase_price'];
        $insertingRow->retail_price = $validatedData['retail_price'];
        $insertingRow->image = $validatedData['image'];
        $insertingRow->vat = $validatedData['vat'];
        $insertingRow->unit_id = $validatedData['unit_id'];
        $insertingRow->status = 1;
        $insertingRow->created_by = auth()->user()->id;
        $insertingRow->updated_at = null;
        $insertingRow->save();
        $insertingRow->categories()->sync($validatedData['category']);
        return redirect()->route('item.index')->with('success', 'Item Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $id = decrypt($id);
        $data = Item::find($id);
        return view('items.view-details', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = decrypt($id);
        $categories = Category::all();
        $item = Item::with('categories')->where('id', '=', $id)->get()->first();
        if(!$item){
            return redirect()->route('item.index');
        }
        return view('items.edit', ['item'=>$item, 'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $id = decrypt($id);
        $updatingRow = Item::find($id);
        $this->validate($request, [
            'name'  =>  'required|unique:items,name, '.$id,
            'item_code'  =>  'required',
            'unit_id'  =>  'required',
            'purchase_price'    =>  'required',
            'retail_price'      =>  '',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'vat'  =>  '',
            'category'  => 'required',
            'status'  => 'required',
        ]);

        $updatingRow->name = $request->name;
        $updatingRow->item_code = $request->item_code;
        $updatingRow->unit_id = $request->unit_id;
        $updatingRow->purchase_price = $request->purchase_price;
        $updatingRow->retail_price = $request->retail_price;
        $updatingRow->vat = $request->vat;

        $updatingRow->status = $request->status;
        $updatingRow->updated_by = auth()->user()->id;

        if($request->hasFile('image')){
            $image = $request->file('image');
            $uploadedImage = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('images/items');
            if ($updatingRow->image != null){
                unlink($destinationPath.'/'.$updatingRow->image);
            }
            $image->move($destinationPath, $uploadedImage);
            $updatingRow['image'] = $uploadedImage;
        }
        $updatingRow->update();
        $updatingRow->categories()->sync($request->category);
        return redirect()->route('item.index')->with('success', 'Item Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id = decrypt($id);
        $delRow = Item::find($id);
        $delRow->delete();
        return redirect()->route('item.index')->with('success-message', 'Item Deleted Successfully');
    }
}

resources/views/items/categories/create.blade.php
@extends('layouts.app')
@section('title', 'Item Categories')
@section('block-header', 'Add Category')
@section('brd1', 'Items & Stocks')
@section('brd2', 'Category')
@section('brd3', 'Add Category')


@section('content')
    <div class="card-body">
        @include('layouts.messages')
        {!! Form::open(['route' => 'category.store', 'method' => 'POST']) !!}
            @include('items.categories.form')
            <div class="row">
                <div class="col-sm-6">
                    <a href="{{route('category.index')}}" class="btn btn-danger" type="submit">Back</a>
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

@push('js')
    <script>
        var inputBox = document.getElementById('catName');

        inputBox.onkeyup = function(){
            document.getElementById('catSlug').value = inputBox.value.replace(/\s+/g, '-').toLowerCase();
        }
    </script>
@endpush

resources/views/items/categories/edit.blade.php
@extends('layouts.app')
@section('title', 'Item Categories')
@section('block-header', 'Edit Item Category')
@section('brd1', 'Items & Stocks')
@section('brd2', 'Category')
@section('brd3', 'Edit Category')

@section('content')
    <div class="card-body">
        @include('layouts.messages')
        {!! Form::model($category, ['method' => 'patch', 'route' => ['category.update', ['category' =>$category->id]]]) !!}
        @include('items.categories.form')

        <div class="row">
            <div class="col-sm-6">
                <a href="{{route('category.index')}}" class="btn btn-danger" type="submit">Back</a>
                <button class="btn btn-primary" type="submit">Update</button>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

@push('css')
    <link rel="stylesheet" href="{{asset('inpos/plugins/bootstrap-select/css/bootstrap-select.css')}}">
@endpush

@push('js')
    <script>
        var inputBox = document.getElementById('catName');

        inputBox.onkeyup = function(){
            document.getElementById('catSlug').value = inputBox.value.replace(/\s+/g, '-').toLowerCase();
        }
    </script>
@endpush

resources/views/items/categories/form.blade.php
<div class="row clearfix">
    <div class="col-md-6">
        <div class="mb-3 mt-3">
            <label class="form-label" for="catName">Category Name (Required)***</label>
            {!! Form::text('name', null, ['class'=>'form-control', 'id'=>'catName']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="mb-3 mt-3">
            <label class="form-label" for="catSlug">Category Code (Required)***</label>
            {!! Form::text('code', null, ['class'=>'form-control', 'id'=>'catSlug']) !!}
        </div>
    </div>

    <div class="col-md-6">
        <div class="mb-3 mt-3">
            <label class="form-label" for="">Category Description</label>
            {!! Form::text('description', null, ['class'=>'form-control']) !!}
        </div>
    </div>

    <div class="col-md-6">
        <div class="mb-3 mt-3">
            <label class="form-label" for="">Status (Required)***</label>
            @if(isset($category))
                {!! Form::select('status', ['1' => 'Active', '2'=>'Inactive'], null, ['class'=>'form-control select2']) !!}
            @else
                {!! Form::select('status', ['1' => 'Active'], null, ['class'=>'form-control select2', 'disabled'=>'disabled']) !!}
            @endif
        </div>
    </div>

</div>

resources/views/items/categories/index.blade.php
@extends('layouts.app')
@section('title', 'Categories')
@section('block-header', 'Categories')
@section('brd1', 'Items & Stocks')
@section('brd2', 'Category')
@section('content')

    <div class="card-body">
        <a href="{{route('category.create')}}" class="btn btn-success">Add New Item Category</a>
    </div>

    <div class="card-body">
        <div class="tab-content">
            <div class="tab-pane show active" id="alt-pagination-preview">
                <table id="get-category" data-form="deleteForm" class="table table-bordered table-striped table-hover">
                    <thead class="thead-color">
                    <tr>
                        <th>SL</th>
                        <th>Name</th>
                        <th>Code</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Created By</th>
                        <th>Created At</th>
                        <th>Updated By</th>
                        <th>Updated At</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script>


        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#get-category').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                // scrollY: "500px",
                ajax: '{{ url('get-category-list') }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'id' },
                    { data: 'name', name: 'name'},
                    { data: 'code', name: 'code'},
                    { data: 'description', name: 'description'},
                    { data: 'status', name: 'status',
                        render:
                            function(data, type, row) {
                                if (data == 1){
                                    $status = '<a class="badge badge-success text-center">Active</a>';
                                }else {
                                    $status = '<a class="badge badge-danger text-center">Inactive</a>';
                                }
                                return $status;
                            }
                    },
                    { data: 'created_by', name: 'created_by'},
                    { data: 'created_at', name: 'created_at'},
                    { data: 'updated_by', name: 'updated_by'},
                    { data: 'updated_at', name: 'updated_at'},
                    {data: 'action', name: 'action', orderable: false,
                        render:
                            function(data, type, row) {
                                // return '<span class="btn btn-primary" id="modalView" onclick="journalView('+data+')">Details</span>';
                                return '<div style="text-align:center" class="action-btn">'+
                                    '<a class="btn btn-info btn-sm" href="category/'+data+'/edit"><i class="far fa-edit"></i></a>'
                            }
                    },
                ],
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal( {
                            header: function ( row ) {
                                var data = row.data();
                                return 'Details for '+data.name;
                            }
                        } ),
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll( {
                            tableClass: 'table'
                        } )
                    }
                },
                order: [[ 0, "desc" ]],
            });
        });
    </script>

    <script>
        $(document).ready(function(){
            $(".btn").click(function(){
                $("#deleteModal").modal('show');
            });
        });
    </script>
@endpush