routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/profile/{id}', 'UserController@showUserProfile')->middleware('mydata')->name('showuserprofile');
Route::post('/user/profile/{id}', 'UserController@updateUserProfile')->name('updateuserprofile');
Route::resource('/customer', 'CustomerController');
Route::get('/get-customer-list', 'CustomerController@list')->name('get-customer-list');
Route::post('/customer/import', 'CustomerController@import')->name('customer.import');
Route::resource('/supplier', 'SupplierController');
Route::get('/get-supplier-list', 'SupplierController@list')->name('get-supplier-list');
Route::resource('/employee', 'EmployeeController');
Route::resource('/category', 'CategoryController');
Route::get('/get-category-list', 'CategoryController@list')->name('get-category-list');
Route::resource('/unit', 'UnitController');
Route::get('/get-unit-list', 'UnitController@list')->name('get-unit-list');
Route::resource('/item', 'ItemController');
Route::get('/get-item-list', 'ItemController@list')->name('get-item-list');
Route::get('/pos', 'PosController@index')->name('posindex');
Route::post('/pos', 'PosController@addToCart')->name('posaddtocart');
Route::post('/deletecart', 'PosController@deleteCartItem')->name('deletecartitem');
Route::post('/deleteallcart', 'PosController@deleteAllCartItem')->name('deleteallcartitem');
Route::resource('/orderbook', 'OrderBookController');
Route::get('/get-order-book-list', 'OrderBookController@list')->name('get-order-book-list');
Route::get('/account', 'AccountController@index')->name('account.index');
Route::post('/account', 'AccountController@store')->name('account.store');
Route::post('/account/edit', 'AccountController@edit')->name('account.edit');
Route::delete('/account/{account}', 'AccountController@destroy')->name('account.destroy');
Route::post('/account/update', 'AccountController@update')->name('account.update');
Route::get('/error', 'ErrorController@err404')->name('404error');
Route::post('/pos/invoice', 'PosController@itemSellInvoiceShow')->name('sellInvoice.show');
Route::resource('/designation', 'DesignationController');
Route::resource('/pay-salary', 'PaySalaryController');
Route::resource('/attendance', 'AttendanceController');
Route::get('/get-attendance-list', 'AttendanceController@getAattendance')->name('get-attendance-list');
Route::resource('/daily-in', 'DailyInController');
Route::post('/get-daily-in-list', 'DailyInController@list')->name('get-daily-in-list');
Route::resource('/daily-out', 'DailyOutController');
Route::post('/get-daily-out-list', 'DailyOutController@list')->name('get-daily-out-list');
Route::resource('/share-holder', 'ShareHolderController');
Route::get('/get-share-holder', 'ShareHolderController@list')->name('get-share-holder');
Route::resource('/capital-management', 'CapitalManagementController');
Route::post('/get-capital-management-list', 'CapitalManagementController@list')->name('get-capital-management-list');
Route::resource('/buy', 'BuyController');
Route::get('/get-buy-list', 'BuyController@list')->name('get-buy-list');
Route::resource('/sell', 'SellController');
Route::get('/sell-buy-list', 'SellController@list')->name('sell-buy-list');
Route::post('/get-price', 'OrderBookController@getPrice')->name('get-price');
Route::resource('/stock', 'StockController');
Route::get('/get-stock-list', 'StockController@list')->name('get-stock-list');
Route::post('/get-stock-list-from-item', 'StockController@listFromItem')->name('get-stock-list-from-item');
Route::post('/stock/get-unit', 'StockController@getUnit')->name('stock.get-unit');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    public function categories(){
        return $this->belongsToMany(Category::class, 'category_item');
    }

    public function unit(){
        return $this->belongsTo(Unit::class, 'unit_id', 'id');
    }



    protected $fillable = [
        'name',
        'item_code',
        'purchase_price',
        'retail_price',
        'image',
        'discount',
        'description',
        'unit_id',
        'status_id',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
    ];


    public function stocks(){
        return $this->hasMany(Stock::class, 'item_id', 'id')->orderBy('stock_date', 'desc');
    }

    public static function getAllItemsByArray()
    {
        try {
            // Validate the value...
            $datas = Item::all()->where('status', 1);
            if (count($datas) > 0){
                foreach ($datas as $item) {
                    $data[$item->id] = $item->name;
                }

                return $data;
            }

        } catch (\Throwable $e) {
            return false;
        }
    }

    public static function getNameById($user_id)
    {
        try {
            // Validate the value...
            $user = Item::where('id', $user_id)->pluck('name')->first();
            return $user;
        } catch (\Throwable $e) {
            return false;
        }
    }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Item;
use Faker\Provider\File;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::with('categories')->get();
        return view('items.index', ['items'=>$items]);
    }


    public function list(){
        $data = Item::select('*')->with('categories');
        return DataTables::of($data)
            ->editColumn('name', function($data){
                return $data->name;
            })
            ->editColumn('item_code', function($data){
                return $data->item_code;
            })
            ->editColumn('purchase_price', function($data){
                return $data->purchase_price;
            })
            ->editColumn('retail_price', function($data){
                return $data->retail_price;
            })
            ->editColumn('quantity', function($data){
                return $data->quantity;
            })
            ->editColumn('vat', function($data){
                return $data->vat;
            })
            ->editColumn('image', function($data){
                $url= asset('/images/items/'.$data->image);
                return '<img height="100" width="100" src="'.$url.'" alt="">';
            })
            ->editColumn('description', function($data){
                return $data->description;
            })
            ->addColumn('unit', function($data){
                return $data->unit ? $data->unit->name : '';
            })
            ->editColumn('category', function($data){
                $datas = [];
                foreach ($data->categories as $category){
                    $datas[] = $category->name;
                }

                return implode(" || ",$datas);
            })
            ->editColumn('status', function($data){
                return $data->status;
            })
            ->editColumn('created_by', function($data){
                return getUserById($data->created_by);
            })
            ->editColumn('updated_by', function($data){
                $user = getUserById($data->updated_by);
                return $user;
            })
            ->editColumn('created_at', function($data){
                return $data->created_at;
            })
            ->editColumn('updated_at', function($data){
                return $data->updated_at;
            })
            ->addColumn('action', function($data){
                return encrypt($data->id);
            })
            ->rawColumns(['image', 'action'])
            ->addIndexColumn()
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('items.create', ['categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */


    public function store(Request $request)
    {
        $validatedData = $this->validate($request, [
            'name'  =>  'required|unique:items',
            'item_code'  =>  'required',
            'unit_id'  =>  'required',
            'purchase_price'    =>  'required',
            'retail_price'      =>  '',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'vat'  =>  '',
            'category'  => 'required',
            'status'  => 'required',
        ]);

        $image = $request->file('image');
        if($request->hasFile('image')){
            $uploadedImage = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images/items');
            $image->move($destinationPath, $uploadedImage);
            $validatedData['image'] = $uploadedImage;
        }else{
            $validatedData['image'] = null;
        }

        $insertingRow = new Item();
        $insertingRow->name = $validatedData['name'];
        $insertingRow->item_code = $validatedData['item_code'];
        $insertingRow->purchase_price = $validatedData['purchase_price'];
        $insertingRow->retail_price = $validatedData['retail_price'];
        $insertingRow->image = $validatedData['image'];
        $insertingRow->vat = $validatedData['vat'];
        $insertingRow->unit_id = $validatedData['unit_id'];
        $insertingRow->status = 1;
        $insertingRow->created_by = auth()->user()->id;
        $insertingRow->updated_at = null;
        $insertingRow->save();
        $insertingRow->categories()->sync($validatedData['category']);
        return redirect()->route('item.index')->with('success', 'Item Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $id = decrypt($id);
        $data = Item::find($id);
        return view('items.view-details', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = decrypt($id);
        $categories = Category::all();
        $item = Item::with('categories')->where('id', '=', $id)->get()->first();
        if(!$item){
            return redirect()->route('item.index');
        }
        return view('items.edit', ['item'=>$item, 'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $id = decrypt($id);
        $updatingRow = Item::find($id);
        $this->validate($request, [
            'name'  =>  'required|unique:items,name, '.$id,
            'item_code'  =>  'required',
            'unit_id'  =>  'required',
            'purchase_price'    =>  'required',
            'retail_price'      =>  '',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'vat'  =>  '',
            'category'  => 'required',
            'status'  => 'required',
        ]);

        $updatingRow->name = $request->name;
        $updatingRow->item_code = $request->item_code;
        $updatingRow->unit_id = $request->unit_id;
        $updatingRow->purchase_price = $request->purchase_price;
        $updatingRow->retail_price = $request->retail_price;
        $updatingRow->vat = $request->vat;

        $updatingRow->status = $request->status;
        $updatingRow->updated_by = auth()->user()->id;

        if($request->hasFile('image')){
            $image = $request->file('image');
            $uploadedImage = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('images/items');
            if ($updatingRow->image != null){
                unlink($destinationPath.'/'.$updatingRow->image);
            }
            $image->move($destinationPath, $uploadedImage);
            $updatingRow['image'] = $uploadedImage;
        }
        $updatingRow->update();
        $updatingRow->categories()->sync($request->category);
        return redirect()->route('item.index')->with('success', 'Item Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id = decrypt($id);
        $delRow = Item::find($id);
        $delRow->delete();
        return redirect()->route('item.index')->with('success-message', 'Item Deleted Successfully');
    }
}

resources/views/items/create.blade.php
@extends('layouts.pos')
@section('title', 'Items')
@section('block-header', 'Add New Item')
@section('head')
    <link rel="stylesheet" type="text/css" href="{{asset('inpos/css/component.css')}}" />
    <style>
        #file-1 {
            display: none;
        }
        .inputfile + label{
            font-size: .8rem;
        }
    </style>
    @endsection
@section('footer')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#spinnerInput').spinner({'min':0, 'max':99999999});
    </script>
    <script src="{{asset('inpos/js/custom-file-input.js')}}"></script>
@endsection
@section('content')
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="body">
                    @include('layouts.messages')
                    {!! Form::open(['route' => 'item.store', 'method'=>'POST', 'files' => true]) !!}
                        @include('items.form')
                    <hr>
                    <div class="text-center">
                        <a href="{{route('item.index')}}" class="btn btn-danger" type="submit">Back</a>
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/items/delete-modal.blade.php
<div id="deleteModal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

resources/views/items/edit.blade.php
@extends('layouts.pos')
@section('title', 'Edit Item')
@section('block-header', 'Edit Item')
@section('head')
    <link rel="stylesheet" type="text/css" href="{{asset('inpos/css/component.css')}}" />
    <style>
        #file-1 {
            display: none;
        }
        .inputfile + label{
            font-size: .8rem;
        }
    </style>
@endsection
@section('footer')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#blah')
                        .attr('src', e.target.result)
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <script src="{{asset('inpos/js/custom-file-input.js')}}"></script>
@endsection
@section('content')
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="body">
                    @include('layouts.messages')
{{--                    <form action="{{route('item.update', $item->id)}}" method="post" enctype="multipart/form-data">--}}
                    {!! Form::model($item, ['method' => 'patch', 'route' => ['item.update', ['item' => encrypt($item->id)]],  'files' => true]) !!}
                        @include('items.form')
                        <div class="row">
                            <div class="col-sm-6">
                                <a href="{{route('item.index')}}" class="btn btn-danger" type="submit">Back</a>
                                <button class="btn btn-primary" type="submit">Update</button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/items/form.blade.php
<div class="row clearfix">
    <div class="col-md-3">
        <label for="name">Name (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::text('name', null, ['class'=>'form-control', 'autocomplete'=>'off', 'required'=>'required', 'tabindex' => '1']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <label for="item_code">Item Code (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::text('item_code', null, ['class'=>'form-control', 'autocomplete'=>'off', 'required'=>'required', 'tabindex' => '2']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <label for="item_code">Select Category (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::select('category[]', categories() ? categories() : [], isset($item) ? $item->categories : null, ['class'=>'select2', 'multiple'=>'multiple', 'autocomplete'=>'off', 'required'=>'required', 'tabindex' => '3']) !!}
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <label for="retail_price">Purchase Price (Required)***</label>
        <div class="input-group spinner" data-trigger="spinner">
            <div class="form-line">
                {{--                                        <input class="form-control text-center" type="number" name="retail_price"  value="0" data-rule="currency">--}}
                {!! Form::number('purchase_price', null, ['class'=>'form-control text-center', 'autocomplete'=>'off', 'required'=>'required', 'tabindex' => '4']) !!}
            </div>
            <span class="input-group-addon">
                <a href="javascript:;" class="spin-up" data-spin="up"><i class="glyphicon glyphicon-chevron-up"></i></a>
                <a href="javascript:;" class="spin-down" data-spin="down"><i class="glyphicon glyphicon-chevron-down"></i></a>
            </span>
        </div>
    </div>

    <div class="col-md-3">
        <label for="retail_price">Retail Price</label>
        <div class="input-group spinner" data-trigger="spinner">
            <div class="form-line">
                {{--                                        <input class="form-control text-center" type="number" name="retail_price"  value="0" data-rule="currency">--}}
                {!! Form::number('retail_price', null, ['class'=>'form-control text-center', 'autocomplete'=>'off', 'tabindex' => '5']) !!}
            </div>
            <span class="input-group-addon">
                <a href="javascript:;" class="spin-up" data-spin="up"><i class="glyphicon glyphicon-chevron-up"></i></a>
                <a href="javascript:;" class="spin-down" data-spin="down"><i class="glyphicon glyphicon-chevron-down"></i></a>
            </span>
        </div>
    </div>
    <div class="col-md-3">
        <label for="vat">Vat in % (Required)***</label>
        <div class="input-group spinner" data-trigger="spinner">
            <div class="form-line">
                {{--                                        <input class="form-control text-center" type="number" name="vat"  value="0" data-rule="currency">--}}
                {!! Form::number('vat', 0, ['class'=>'form-control text-center', 'autocomplete'=>'off', 'required'=>'required', 'tabindex' => '6']) !!}
            </div>
            <span class="input-group-addon">
                                        <a href="javascript:;" class="spin-up" data-spin="up"><i class="glyphicon glyphicon-chevron-up"></i></a>
                                        <a href="javascript:;" class="spin-down" data-spin="down"><i class="glyphicon glyphicon-chevron-down"></i></a>
                                    </span>
        </div>
    </div>

{{--    <div class="col-md-2">--}}
{{--        <label for="quantity">Quantity (Required)***</label>--}}
{{--        <div class="input-group spinner" data-trigger="spinner">--}}
{{--            <div class="form-line">--}}
{{--                --}}{{--                                        <input id="spinnerInput" class="form-control text-center" type="text" name="quantity"  value="0" data-rule="quantity">--}}
{{--                {!! Form::number('quantity', null, ['class'=>'form-control text-center', 'data-rule'=>'quantity', 'id'=>'spinnerInput', 'autocomplete'=>'off', 'required'=>'required']) !!}--}}
{{--            </div>--}}
{{--            <span class="input-group-addon">--}}
{{--                    <a href="javascript:;" class="spin-up" data-spin="up"><i class="glyphicon glyphicon-chevron-up"></i></a>--}}
{{--                    <a href="javascript:;" class="spin-down" data-spin="down"><i class="glyphicon glyphicon-chevron-down"></i></a>--}}
{{--                </span>--}}
{{--        </div>--}}
{{--    </div>--}}

        <div class="col-md-3">
            <label for="unit_id">Unit (Required)***</label>
            <div class="form-group">
                <div class="form-line">
                    {!! Form::select('unit_id', units() ? [''=>'']+units() : [], isset($stock) ? $stock->unit_id : null, ['class'=>'select2', 'autocomplete'=>'off', 'required'=>'required']) !!}
                </div>
            </div>
        </div>

    <div class="col-md-3">
        <label for="name">Status (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                @if(isset($item))
                    {!! Form::select('status', ['1' => 'Active', '2'=>'Inactive'], null, ['class'=>'select2', 'tabindex' => '7']) !!}
                @else
                    {!! Form::select('status', ['1' => 'Active'], null, ['class'=>'select2', 'tabindex' => '7']) !!}
                @endif
            </div>
        </div>
    </div>

{{--    <div class="col-md-3">--}}
{{--        <label for="quantity">Quantity (Required)***</label>--}}
{{--        <div class="form-group">--}}
{{--            <div class="form-line">--}}
{{--                {!! Form::number('quantity', null, ['class'=>'form-control', 'id'=>'quantity']) !!}--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
</div>

<div class="row clearfix">
    <div style="text-align: center" class="col-md-12">
        <label for="image">Item Image</label>
        <div style="text-align: center" class="box">
            @if(isset($item))
                <img  id="blah" class="img-responsive" src="{{asset('images/items/'.$item->image)}}" width="250" height="200" alt="" >
            @else
                <img id="blah" class="img-responsive" src="{{asset('images/items/no_image.png')}}" width="250" height="200" alt="" >
            @endif
            <br>
            <br>
            <input tabindex="8" accept="image/*" type="file" name="image" id="file-1" class="inputfile inputfile-1" data-multiple-caption="{count} files selected" multiple onchange="readURL(this)"/>
            <label for="file-1"><svg xmlns="http://www.w3.org/2000/svg" width="15" height="12" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span>Choose a file&hellip;</span></label>
        </div>
    </div>
</div>

resources/views/items/index.blade.php
@extends('layouts.pos')
@section('title', 'Items')
@section('block-header', 'Items')
@section('content')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <a href="{{route('item.create')}}" class="btn btn-success">Add New Item</a>
                </div>

                <div class="body">
                    <table id="get-item-list" data-form="deleteForm" class="table table-bordered table-striped table-hover">
                        <thead class="thead-color">
                        <tr>
                            <th>Sl. No.</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Category</th>
                            <th>Purchase Price</th>
                            <th>Retail Price</th>
                            <th>vat</th>
                            <th>Image</th>
                            <th>Status</th>
{{--                            <th>Created By</th>--}}
{{--                            <th>Created At</th>--}}
{{--                            <th>Updated By</th>--}}
{{--                            <th>Updated At</th>--}}
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{{--    <form style="display: inline;" action="{{route('item.destroy', $item->id)}}" method="post" onsubmit="return confirm('Are you sure you want to delete {{$item->name}}');">--}}
{{--        {{ method_field('DELETE') }}--}}
{{--        @csrf--}}
{{--        <button class="btn btn-danger waves-effect" type="submit">--}}
{{--            <i class="material-icons">delete</i>--}}
{{--        </button>--}}
{{--    </form>--}}
@endsection


@push('scripts')
    <script>


        $(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#get-item-list').DataTable({
                processing: true,
                serverSide: true,
                // responsive: true,
                // scrollY: "500px",
                ajax: '{{ url('get-item-list') }}',
                columns: [
                    { data: 'DT_RowIndex', name: 'id' },
                    { data: 'name', name: 'name'},
                    { data: 'item_code', name: 'item_code'},
                    { data: 'category', name: 'category'},
                    { data: 'purchase_price', name: 'purchase_price'},
                    { data: 'retail_price', name: 'retail_price'},
                    { data: 'vat', name: 'vat'},
                    { data: 'image', name: 'image'},
                    { data: 'status', name: 'status',
                        render:
                            function(data, type, row) {
                                if (data == 1){
                                    $status = '<a class="badge badge-success text-center">Active</a>';
                                }else {
                                    $status = '<a class="badge badge-danger text-center">Inactive</a>';
                                }
                                return $status;
                            }
                    },
                    // { data: 'created_by', name: 'created_by'},
                    // { data: 'created_at', name: 'created_at'},
                    // { data: 'updated_by', name: 'updated_by'},
                    // { data: 'updated_at', name: 'updated_at'},
                    {data: 'action', name: 'action', orderable: false,
                        render:
                            function(data, type, row) {
                                // return '<span class="btn btn-primary" id="modalView" onclick="journalView('+data+')">Details</span>';
                                return '<div style="text-align:center" class="action-btn">'+
                                    '<a class="btn btn-success btn-sm" href="item/'+data+'">View Details</a>'+
                                    '<a class="btn btn-info btn-sm" href="item/'+data+'/edit">Edit</a>'
                            }
                    },
                ],
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal( {
                            header: function ( row ) {
                                var data = row.data();
                                return 'Details for '+data.name;
                            }
                        } ),
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll( {
                            tableClass: 'table'
                        } )
                    }
                },
                order: [[ 0, "desc" ]],
            });
        });
    </script>

{{--    <script>--}}
{{--        $(document).ready(function(){--}}
{{--            $(".btn").click(function(){--}}
{{--                $("#deleteModal").modal('show');--}}
{{--            });--}}
{{--        });--}}
{{--    </script>--}}

@endpush