routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/profile/{id}', 'UserController@showUserProfile')->middleware('mydata')->name('showuserprofile');
Route::post('/user/profile/{id}', 'UserController@updateUserProfile')->name('updateuserprofile');
Route::resource('/customer', 'CustomerController');
Route::get('/get-customer-list', 'CustomerController@list')->name('get-customer-list');
Route::post('/customer/import', 'CustomerController@import')->name('customer.import');
Route::resource('/supplier', 'SupplierController');
Route::get('/get-supplier-list', 'SupplierController@list')->name('get-supplier-list');
Route::resource('/employee', 'EmployeeController');
Route::resource('/category', 'CategoryController');
Route::get('/get-category-list', 'CategoryController@list')->name('get-category-list');
Route::resource('/unit', 'UnitController');
Route::get('/get-unit-list', 'UnitController@list')->name('get-unit-list');
Route::resource('/item', 'ItemController');
Route::get('/get-item-list', 'ItemController@list')->name('get-item-list');
Route::get('/pos', 'PosController@index')->name('posindex');
Route::post('/pos', 'PosController@addToCart')->name('posaddtocart');
Route::post('/deletecart', 'PosController@deleteCartItem')->name('deletecartitem');
Route::post('/deleteallcart', 'PosController@deleteAllCartItem')->name('deleteallcartitem');
Route::resource('/orderbook', 'OrderBookController');
Route::get('/get-order-book-list', 'OrderBookController@list')->name('get-order-book-list');
Route::get('/account', 'AccountController@index')->name('account.index');
Route::post('/account', 'AccountController@store')->name('account.store');
Route::post('/account/edit', 'AccountController@edit')->name('account.edit');
Route::delete('/account/{account}', 'AccountController@destroy')->name('account.destroy');
Route::post('/account/update', 'AccountController@update')->name('account.update');
Route::get('/error', 'ErrorController@err404')->name('404error');
Route::post('/pos/invoice', 'PosController@itemSellInvoiceShow')->name('sellInvoice.show');
Route::resource('/designation', 'DesignationController');
Route::resource('/pay-salary', 'PaySalaryController');
Route::resource('/attendance', 'AttendanceController');
Route::get('/get-attendance-list', 'AttendanceController@getAattendance')->name('get-attendance-list');
Route::resource('/daily-in', 'DailyInController');
Route::post('/get-daily-in-list', 'DailyInController@list')->name('get-daily-in-list');
Route::resource('/daily-out', 'DailyOutController');
Route::post('/get-daily-out-list', 'DailyOutController@list')->name('get-daily-out-list');
Route::resource('/share-holder', 'ShareHolderController');
Route::get('/get-share-holder', 'ShareHolderController@list')->name('get-share-holder');
Route::resource('/capital-management', 'CapitalManagementController');
Route::post('/get-capital-management-list', 'CapitalManagementController@list')->name('get-capital-management-list');
Route::resource('/buy', 'BuyController');
Route::get('/get-buy-list', 'BuyController@list')->name('get-buy-list');
Route::resource('/sell', 'SellController');
Route::get('/sell-buy-list', 'SellController@list')->name('sell-buy-list');
Route::post('/get-price', 'OrderBookController@getPrice')->name('get-price');
Route::resource('/stock', 'StockController');
Route::get('/get-stock-list', 'StockController@list')->name('get-stock-list');
Route::post('/get-stock-list-from-item', 'StockController@listFromItem')->name('get-stock-list-from-item');
Route::post('/stock/get-unit', 'StockController@getUnit')->name('stock.get-unit');

app/Models/DailyIn.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DailyIn extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/DailyInController.php
<?php

namespace App\Http\Controllers;

use App\Models\DailyIn;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class DailyInController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $datas = DailyIn::select('*');
        return view('daily_in.index');
    }

    public function list(Request $request){
//        $status = $request->input('status');
//        $date = explode(" - ", $request->input('date'));
////        $dateOne = date_create($date['0']);
////        $dateTwo = date_create($date['1']);
////        $date_from = date_format($dateOne,"Y-m-d");
////        $date_to = date_format($dateTwo,"Y-m-d");
//        dd($date['0']);
//        $data = (new DailyIn())->newQuery();
//        $dateToAddOne = date('Y-m-d', strtotime($date_to . " +1 days"));
//
//        if (isset($date_from) && isset($date_to)) {
//            $data->whereBetween('daily_ins.date', [$date_from, $dateToAddOne]);
//        }
//
//        if (isset($date_from) && !isset($date_to)) {
//            $data->whereDate('daily_ins.date', '>=', $date_from);
//        }
//
//        if (isset($date_to) && !isset($date_from)) {
//            $data->whereDate('daily_ins.date', '<=', $date_to);
//        }
////        return $data

        $data = DailyIn::all();
        return DataTables::of($data)
            ->editColumn('name', function($data){
                return $data->name;
            })
            ->editColumn('amount', function($data){
                return $data->amount;
            })
            ->editColumn('date', function($data){
                return $data->date;
            })
            ->editColumn('status', function($data){
                return $data->status;
            })
            ->editColumn('created_by', function($data){
                return getUserById($data->created_by);
            })
            ->editColumn('updated_by', function($data){
                $user = getUserById($data->updated_by);
                return $user;
            })
            ->editColumn('created_at', function($data){
                return $data->created_at;
            })
            ->editColumn('updated_at', function($data){
                return $data->updated_at;
            })
            ->addColumn('action', function($data){
                return $data->id;
            })
            ->rawColumns(['action'])
            ->addIndexColumn()
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('daily_in.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newData = $this->validate($request, [
            'name' =>  'required',
            'amount' =>  'required|numeric',
            'date' =>  'required',
        ]);
        $newData['status'] = 1;
        $newData['created_by'] = Auth::user()->id;
        $newData['updated_at'] = null;
        DailyIn::create($newData);
        return redirect()->route('daily-in.index')->with('success', 'New Record Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\DailyIn  $dailyIn
     * @return \Illuminate\Http\Response
     */
    public function show(DailyIn $dailyIn)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DailyIn  $dailyIn
     * @return \Illuminate\Http\Response
     */
    public function edit(DailyIn $dailyIn)
    {
        return view('daily_in.edit', ['dailyIn'=>$dailyIn]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\DailyIn  $dailyIn
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, DailyIn $dailyIn)
    {
        $updateDailyIn = DailyIn::find($dailyIn->id);
        $updateData = $this->validate($request, [
            'name' =>  'required',
            'amount' =>  'required|numeric',
            'date' =>  'required',
            'status' =>  '',
        ]);
        $updateData['updated_by'] = Auth::user()->id;
        $updateDailyIn->update($updateData);
        return redirect()->route('daily-in.index')->with('success', 'Data Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DailyIn  $dailyIn
     * @return \Illuminate\Http\Response
     */
    public function destroy(DailyIn $dailyIn)
    {
        //
    }
}

resources/views/daily_in/create.blade.php
@extends('layouts.pos')
@section('title', 'Daily In')
@section('block-header', 'Add Daily In')

@section('content')
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="body">
                    @include('layouts.messages')
                    {!! Form::open(['route' => 'daily-in.store', 'method' => 'post']) !!}
                        @include('daily_in.form')
                        <div class="row">
                            <div class="col-sm-6">
                                <a href="{{route('daily-in.index')}}" class="btn btn-danger">Back</a>
                                <button class="btn btn-primary" type="submit">Create</button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/daily_in/edit.blade.php
@extends('layouts.pos')
@section('title', 'Daily In')
@section('block-header', 'Edit Daily In')

@section('content')
    <div class="row clearfix">
        <div class="col-lg-12">
            <div class="card">
                <div class="body">
                    @include('layouts.messages')

                    {!! Form::model($dailyIn, ['method' => 'patch', 'route' => ['daily-in.update', ['daily_in' =>$dailyIn->id]]]) !!}
                    @include('daily_in.form')

                    <div class="row">
                        <div class="col-sm-6">
                            <a href="{{route('daily-in.index')}}" class="btn btn-danger" type="submit">Back</a>
                            <button class="btn btn-primary" type="submit">Update</button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/daily_in/filter.blade.php
<div class="form-group d-flex justify-content-end">
    <div class="form-line">
        {!! Form::text('datefilter', null, ['class' => 'form-control', 'id'=>'date', 'placeholder' => 'Select Date Rang', 'autocomplete'=>'off']) !!}
    </div>
    <div style="margin-left: .5rem" class="form-line">
        {!! Form::select('status', [''=>'', '1' => 'Active', '2'=>'Inactive'], null, ['id'=>'status', 'class'=>'select2']) !!}
    </div>
    <button id="btn_filter" class="btn btn-success" type="submit">Filter</button>
</div>

@push('css')
    <!-- Date Range Picker Css-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <style>
        .form-group .form-line{
            border-bottom: 1px solid #2E4053;
        }
    </style>
@endpush

@push('scripts')
    <!-- Date Range Picker Js -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <script type="text/javascript">
        $(function() {
            $('input[name="datefilter"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: 'Clear'
                }
            });

            $('input[name="datefilter"]').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
            });

            $('input[name="datefilter"]').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
            });

        });

    </script>
@endpush

resources/views/daily_in/form.blade.php
<div class="row clearfix">
    <div class="col-md-6">
        <label for="name">Name (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::text('name', null, ['class'=>'form-control', 'required'=>'required', 'autocomplete'=>'off']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <label for="name">Amount (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::number('amount', null, ['class'=>'form-control', 'required'=>'required', 'autocomplete'=>'off']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <label for="name">Date (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                {!! Form::date('date', isset($dailyIn) ? $dailyIn->date : \Carbon\Carbon::now(), ['class'=>'form-control', 'required'=>'required', 'autocomplete'=>'off']) !!}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <label for="name">Status (Required)***</label>
        <div class="form-group">
            <div class="form-line">
                @if(isset($dailyIn))
                    {!! Form::select('status', ['1' => 'Active', '2'=>'Inactive'], null, ['class'=>'select2']) !!}
                @else
                    {!! Form::select('status', ['1' => 'Active'], null, ['class'=>'select2', 'disabled'=>'disabled']) !!}
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/daily_in/index.blade.php
@extends('layouts.pos')
@section('title', 'Daily In')
@section('block-header', 'Daily In')
@section('content')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header row">
                    <div class="col-md-6">
                        <div class="d-flex justify-content-start">
                            <a href="{{route('daily-in.create')}}" class="btn btn-success">Add New Record</a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="d-flex justify-content-end">
                            @include('daily_in.filter')
                        </div>
                    </div>
                </div>

                <div class="body">
                    @include('layouts.messages')
                    <div class="table-responsive">
                        <table id="get-daily-in" class="table table-bordered table-hover">
                            <thead class="thead-color">
                            <tr>
                                <th>Sl. No.</th>
                                <th>Record Name</th>
                                <th>Amount</th>
                                <th>Date</th>
                                <th>Status</th>
                                <th>Created By</th>
                                <th>Created At</th>
                                <th>Updated By</th>
                                <th>Updated At</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        filter_datatable();

        function filter_datatable(date,status) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var dataTable = $('#get-daily-in').DataTable({
                processing: true,
                serverSide: true,
                // responsive: true,
                // scrollY: "500px",
                ajax: {
                    url: '{{ url('get-daily-in-list') }}',
                    data:{'date': date, 'status': status},
                    type: 'post'
                },
                columns: [
                    { data: 'DT_RowIndex', name: 'id' },
                    { data: 'name', name: 'name'},
                    { data: 'amount', name: 'amount'},
                    { data: 'date', name: 'date'},
                    { data: 'status', name: 'status',
                        render:
                            function(data, type, row) {
                                if (data == 1){
                                    $status = '<a class="badge badge-success text-center">Active</a>';
                                }else {
                                    $status = '<a class="badge badge-danger text-center">Inactive</a>';
                                }
                                return $status;
                            }
                    },
                    { data: 'created_by', name: 'created_by'},
                    { data: 'created_at', name: 'created_at'},
                    { data: 'updated_by', name: 'updated_by'},
                    { data: 'updated_at', name: 'updated_at'},
                    {data: 'action', name: 'action', orderable: false,
                        render:
                            function(data, type, row) {
                                // return '<span class="btn btn-primary" id="modalView" onclick="journalView('+data+')">Details</span>';
                                return '<div style="text-align:center" class="action-btn">'+
                                    '<a class="btn btn-info btn-sm" href="daily-in/'+row.id+'/edit">Edit</a>'
                            }
                    },
                ],
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal( {
                            header: function ( row ) {
                                var data = row.data();
                                return 'Details for '+data.name;
                            }
                        } ),
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll( {
                            tableClass: 'table'
                        } )
                    }
                },
                order: [[ 0, "desc" ]],
            });

        };

        $('#btn_filter').click(function () {
            var date = $('#date').val();
            var status = $('#status').val();
            $('#get-daily-in').DataTable().destroy();
            filter_datatable(date,status);
        });
    </script>
@endpush